version: '3'

services:
    myrabbitmq:
        image: rabbitmq:3-management
        container_name: myrabbitmq
        expose:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq-network
    otel-collector:
            image: otel/opentelemetry-collector-contrib:0.72.0
            command: ["--config=/etc/otel-collector-config.yaml"]
            volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
            expose:
             - "4317:4317"   # OTLP gRPC receiver
            networks:
                - network-external
                - rabbitmq-network   
    apigateway:
            depends_on:
                - myrabbitmq
            container_name: apigateway
            build:
                context: .
                dockerfile: ./APIGateway/dockerfile
            ports:
                - 8080:8080
            env_file:
                - ./.ops/rabbitmq.env
            networks:
                - rabbitmq-network        
    customerservice:
            depends_on:
                - myrabbitmq
            container_name: customerservice
            build:
                context: .
                dockerfile: ./CustomerService/dockerfile
            env_file:
                - ./.ops/rabbitmq.env
            networks:
                - rabbitmq-network        
    orderservice:
            depends_on:
                - myrabbitmq
            container_name: orderservice
            build:
                context: .
                dockerfile: ./OrderService/dockerfile
            env_file:
                - ./.ops/rabbitmq.env
            networks:
                - rabbitmq-network        
    paymentservice:
            depends_on:
                - myrabbitmq
            container_name: paymentservice
            build:
                context: .
                dockerfile: ./PaymentService/dockerfile
            env_file:
                - ./.ops/rabbitmq.env
            networks:
                - rabbitmq-network        
    productservice:
            depends_on:
                - myrabbitmq
            container_name: productservice
            build:
                context: .
                dockerfile: ./ProductService/dockerfile
            env_file:
                - ./.ops/rabbitmq.env
            networks:
                - rabbitmq-network        
networks:
    rabbitmq-network:
        driver: bridge
    network-external:
        name: otel_network
        external: true
    
