version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  otel-collector:
        image: otel/opentelemetry-collector
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
        - "1888:1888"   # pprof extension
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "4317:4317"   # OTLP gRPC receiver
        - "4318:4318"   # OTLP http receiver
        - "55679:55679" # zpages extension
  apigateway:
        depends_on:
            - rabbitmq
        container_name: apigateway
        build:
            context: .
            dockerfile: ./APIGateway/dockerfile
        ports:
            - 8080:8080
        environment:
            - MQConnectionString=amqp://guest:guest@rabbitmq:5672/
  customerservice:
        depends_on:
            - rabbitmq
        container_name: customerservice
        build:
            context: .
            dockerfile: ./CustomerService/dockerfile
        environment:
            - MQConnectionString=amqp://guest:guest@rabbitmq:5672/
  orderservice:
        depends_on:
            - rabbitmq
        container_name: orderservice
        build:
            context: .
            dockerfile: ./OrderService/dockerfile
        environment:
            - MQConnectionString=amqp://guest:guest@rabbitmq:5672/
  paymentservice:
        depends_on:
            - rabbitmq
        container_name: paymentservice
        build:
            context: .
            dockerfile: ./PaymentService/dockerfile
        environment:
            - MQConnectionString=amqp://guest:guest@rabbitmq:5672/
  productservice:
        depends_on:
            - rabbitmq
        container_name: productservice
        build:
            context: .
            dockerfile: ./ProductService/dockerfile
        environment:
            - MQConnectionString=amqp://guest:guest@rabbitmq:5672/
