version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  apigateway:
        depends_on:
            - rabbitmq
        container_name: apigateway
        build:
            context: .
            dockerfile: ./APIGateway/dockerfile
        ports:
            - 8080:8080