receivers:
  otlp:
    protocols:
      grpc:

processors:
  groupbytrace:
    wait_duration: 10s
    num_traces: 1000
exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [groupbytrace]
      exporters: [logging]