FROM golang:1.19.1-alpine as base

WORKDIR /APP

COPY go.mod ./
COPY go.sum ./

RUN go mod download


COPY ./ProductService/ ./ProductService

COPY ./Utils/ ./Utils

COPY ./MessageHandler/ ./MessageHandler

RUN cd ./ProductService && go build -o ../build/rungo .


## Step 2

FROM golang:1.19.1-alpine

WORKDIR /BUILD


COPY --from=base ./APP/build .

CMD [ "./rungo" ]


