FROM golang:1.20.1-alpine as base

WORKDIR /APP

COPY go.mod ./
COPY go.sum ./

RUN go mod download


COPY ./OrderService/ ./OrderService

COPY ./Utils/ ./Utils

COPY ./MessageHandler/ ./MessageHandler

RUN cd ./OrderService && go build -o ../build/rungo .


## Step 2

FROM golang:1.20.1-alpine

WORKDIR /BUILD


COPY --from=base ./APP/build .

CMD [ "./rungo" ]


