name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build_api:
      needs: prepare_build
      runs-on: ubuntu-latest

      steps:  
      - name: Build and push API Gateway
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./APIGateway/dockerfile
          tags: szmnnagel/siapp-apigateway:latest
  build_customerservice:
      needs: prepare_build
      runs-on: ubuntu-latest
      
      steps:
      - name: Build and push API Gateway
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./CustomerService/dockerfile
          tags: szmnnagel/siapp-customerservice:latest
