name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: ./APIGateway/dockerfile
           tag: siapp-apigateway
         - dockerfile: ./CustomerService/dockerfile
           tag: siapp-customerservice
         - dockerfile: ./OrderService/dockerfile
           tag: siapp-orderservice
         - dockerfile: ./PaymentService/dockerfile
           tag: siapp-paymentservice
         - dockerfile: ./ProductService/dockerfile
           tag: siapp-productservice
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push API Gateway
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          tags: szmnnagel/${{ matrix.tag }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
