name: ON_PR

on:
  pull_request:
    branches: [ master ]


permissions:
  contents: read
  pull-requests: read
  
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - uses: actions/checkout@v3
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: ./APIGateway/dockerfile
         - dockerfile: ./CustomerService/dockerfile
         - dockerfile: ./OrderService/dockerfile
         - dockerfile: ./PaymentService/dockerfile
         - dockerfile: ./ProductService/dockerfile
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
